import { EmailRecord } from '@/types/email';

export const INITIAL_SAMPLE_EMAILS: EmailRecord[] = [
  {
    id: 'em-001',
    sender: 'dean@college.edu',
    subject: 'Semester Fee Deadline - Autumn 2026',
    body: 'Dear Students, The last date for semester fee payment for the Autumn 2026 term is August 25. Failure to pay before the due date will incur late registration penalties and temporary portal suspension.',
    category: 'Education',
    ai_priority: 'HIGH',
    final_priority: 'HIGH',
    action_required: true,
    action: 'Pay the semester fee via college ERP portal',
    deadline: '2026-08-25',
    summary: 'The deadline for semester fee payment is August 25, 2026. Late fees apply after the deadline.',
    confidence: 1.0,
    days_remaining: 5,
    validation_status: 'VALID',
    received_at: '2026-08-20T08:15:00Z',
    created_at: '2026-08-20T08:15:04Z',
  },
  {
    id: 'em-002',
    sender: 'security@cloud-infra.io',
    subject: 'CRITICAL: Mandatory SSL Certificate Rotation Required',
    body: 'Your wildcard SSL certificate for *.production.internal will expire in 48 hours. Please update the certificates in your ingress load balancer immediately to avoid downtime.',
    category: 'Security',
    ai_priority: 'HIGH',
    final_priority: 'HIGH',
    action_required: true,
    action: 'Rotate and deploy wildcard SSL certificate on ingress load balancer',
    deadline: '2026-08-22',
    summary: 'Wildcard SSL certificate expires in 48 hours. Immediate rotation required on production ingress.',
    confidence: 0.98,
    days_remaining: 2,
    validation_status: 'VALID',
    received_at: '2026-08-20T07:42:10Z',
    created_at: '2026-08-20T07:42:12Z',
  },
  {
    id: 'em-003',
    sender: 'billing@aws-billing-notify.com',
    subject: 'Invoice #INV-2026-8941 for Cloud Services Due',
    body: 'Greetings, Your monthly cloud infrastructure invoice of $1,420.50 has been generated. The scheduled payment will be processed on August 28, 2026.',
    category: 'Finance',
    ai_priority: 'MEDIUM',
    final_priority: 'MEDIUM',
    action_required: true,
    action: 'Review invoice charges and ensure corporate credit card balance',
    deadline: '2026-08-28',
    summary: 'Monthly cloud infrastructure invoice of $1,420.50 due on August 28, 2026.',
    confidence: 0.94,
    days_remaining: 8,
    validation_status: 'VALID',
    received_at: '2026-08-20T06:30:22Z',
    created_at: '2026-08-20T06:30:25Z',
  },
  {
    id: 'em-004',
    sender: 'talent-acquisition@techcorp.com',
    subject: 'SIH Finalist Interview Schedule Confirmation',
    body: 'Congratulations! We were impressed by your Smart India Hackathon submission. We would like to schedule a 45-minute technical discussion with our engineering team on August 24 at 3:00 PM IST.',
    category: 'Career',
    ai_priority: 'HIGH',
    final_priority: 'HIGH',
    action_required: true,
    action: 'Confirm calendar invite and test webcam setup',
    deadline: '2026-08-23',
    summary: 'Interview invitation for SIH finalist on August 24. RSVP requested by August 23.',
    confidence: 0.96,
    days_remaining: 3,
    validation_status: 'VALID',
    received_at: '2026-08-20T05:18:45Z',
    created_at: '2026-08-20T05:18:48Z',
  },
  {
    id: 'em-005',
    sender: 'library@university.ac.in',
    subject: 'Book Due Reminder: Distributed Systems Principles',
    body: 'The book "Distributed Systems: Principles and Paradigms (3rd Edition)" checked out on August 6 is due for return on August 27. You may renew online if no holds exist.',
    category: 'Education',
    ai_priority: 'LOW',
    final_priority: 'LOW',
    action_required: true,
    action: 'Renew book online or return to university library desk',
    deadline: '2026-08-27',
    summary: 'Library book return/renewal reminder due on August 27.',
    confidence: 0.91,
    days_remaining: 7,
    validation_status: 'VALID',
    received_at: '2026-08-19T16:05:12Z',
    created_at: '2026-08-19T16:05:14Z',
  },
  {
    id: 'em-006',
    sender: 'newsletter@hackernews-digest.xyz',
    subject: 'HackerNews Weekly Tech Radar #342',
    body: 'Top stories this week: Open-source local LLM inference optimizations, WebAssembly SQLite benchmarks, and modern micro-frontend architectures.',
    category: 'Newsletter',
    ai_priority: 'LOW',
    final_priority: 'LOW',
    action_required: false,
    action: null,
    deadline: null,
    summary: 'Weekly tech news digest covering LLMs, WASM, and web architectures.',
    confidence: 0.88,
    days_remaining: null,
    validation_status: 'VALID',
    received_at: '2026-08-19T11:20:00Z',
    created_at: '2026-08-19T11:20:02Z',
  },
  {
    id: 'em-007',
    sender: 'admin@college-housing.org',
    subject: 'Room Inspection Notice - Block B',
    body: 'Notice to all residents of Block B: Annual room inspections and fire safety checks will occur on August 21 between 10:00 AM and 2:00 PM. Please ensure clear pathways to windows and balconies.',
    category: 'Operations',
    ai_priority: 'MEDIUM',
    final_priority: 'HIGH',
    action_required: true,
    action: 'Ensure room cleanliness and pathway access before 10 AM',
    deadline: '2026-08-21',
    summary: 'Block B room inspection scheduled for August 21, 10 AM to 2 PM.',
    confidence: 0.92,
    days_remaining: 1,
    validation_status: 'VALID',
    received_at: '2026-08-19T09:45:30Z',
    created_at: '2026-08-19T09:45:33Z',
  },
  {
    id: 'em-008',
    sender: 'noreply@researchgate-updates.net',
    subject: 'New citation for your paper on Neural Graph Transformers',
    body: 'Your paper has been cited in "A Survey on Scalable Graph Learning Algorithms". Check the citation graph and metrics.',
    category: 'Research',
    ai_priority: 'LOW',
    final_priority: 'LOW',
    action_required: false,
    action: null,
    deadline: null,
    summary: 'Paper citation notification from ResearchGate.',
    confidence: 0.85,
    days_remaining: null,
    validation_status: 'VALID',
    received_at: '2026-08-18T14:10:00Z',
    created_at: '2026-08-18T14:10:03Z',
  },
  {
    id: 'em-009',
    sender: 'hr-compliance@portal.corp',
    subject: 'Action Required: Submit Annual Workplace Ethics Sign-off',
    body: 'All team members must complete and electronically sign the 2026 Workplace Ethics & Conduct acknowledgment module before August 31.',
    category: 'Compliance',
    ai_priority: 'MEDIUM',
    final_priority: 'MEDIUM',
    action_required: true,
    action: 'Complete ethics course module and sign digital form',
    deadline: '2026-08-31',
    summary: 'Mandatory workplace ethics training module sign-off due by August 31, 2026.',
    confidence: 0.95,
    days_remaining: 11,
    validation_status: 'VALID',
    received_at: '2026-08-18T10:00:15Z',
    created_at: '2026-08-18T10:00:18Z',
  },
  {
    id: 'em-010',
    sender: 'scanner@unverified-mail.com',
    subject: 'Invoice confirmation #unknown-format',
    body: 'Attachment: scan_doc_9912.pdf. Click here to view unverified document.',
    category: 'Spam',
    ai_priority: 'LOW',
    final_priority: 'LOW',
    action_required: false,
    action: null,
    deadline: null,
    summary: 'Potentially suspicious or unparseable email body.',
    confidence: 0.42,
    days_remaining: null,
    validation_status: 'INVALID',
    received_at: '2026-08-17T18:22:00Z',
    created_at: '2026-08-17T18:22:05Z',
  }
];
