import { EmailRecord } from '@/types/email';

export const INITIAL_SAMPLE_EMAILS: EmailRecord[] = [
  {
    id: 'em-001',
    message_id: 'msg-001-dean',
    thread_id: 'thread-edu-1',
    sender: 'dean@college.edu',
    subject: 'Semester Fee Deadline - Autumn 2026',
    body: 'Dear Students, The last date for semester fee payment for the Autumn 2026 term is tomorrow, August 28. Failure to pay before the due date will incur late registration penalties and temporary portal suspension.',
    category: 'Education',
    ai_priority: 'HIGH',
    final_priority: 'HIGH',
    action_required: true,
    action: 'Pay fee via college ERP portal',
    deadline: '2026-08-28',
    summary: 'Your university semester fee payment is due tomorrow. Late penalties apply after the cutoff.',
    confidence: 0.98,
    days_remaining: 1,
    deadline_status: 'TOMORROW',
    should_alert: true,
    validation_status: 'VALID',
    received_at: '2026-08-27T08:15:00Z',
    created_at: '2026-08-27T08:15:04Z',
  },
  {
    id: 'em-002',
    message_id: 'msg-002-ssl',
    thread_id: 'thread-sec-2',
    sender: 'security@cloud-infra.io',
    subject: 'CRITICAL: Mandatory SSL Certificate Rotation Required',
    body: 'Your wildcard SSL certificate for *.production.internal will expire in 48 hours. Please update the certificates in your ingress load balancer immediately to avoid downtime.',
    category: 'Security',
    ai_priority: 'HIGH',
    final_priority: 'HIGH',
    action_required: true,
    action: 'Rotate and deploy wildcard SSL certificate',
    deadline: '2026-08-29',
    summary: 'Wildcard SSL certificate expires in 48 hours. Immediate rotation required on production ingress.',
    confidence: 0.98,
    days_remaining: 2,
    deadline_status: '2 DAYS LEFT',
    should_alert: true,
    validation_status: 'VALID',
    received_at: '2026-08-27T07:42:10Z',
    created_at: '2026-08-27T07:42:12Z',
  },
  {
    id: 'em-004',
    message_id: 'msg-004-sih',
    thread_id: 'thread-career-4',
    sender: 'talent-acquisition@techcorp.com',
    subject: 'SIH Finalist Interview Schedule Confirmation',
    body: 'Congratulations! We were impressed by your Smart India Hackathon submission. We would like to schedule a 45-minute technical discussion with our engineering team on August 30 at 3:00 PM IST.',
    category: 'Career',
    ai_priority: 'HIGH',
    final_priority: 'HIGH',
    action_required: true,
    action: 'Confirm calendar invite and test webcam setup',
    deadline: '2026-08-30',
    summary: 'Interview invitation for SIH finalist on August 30. RSVP requested by August 30.',
    confidence: 0.96,
    days_remaining: 3,
    deadline_status: '3 DAYS LEFT',
    should_alert: true,
    validation_status: 'VALID',
    received_at: '2026-08-27T05:18:45Z',
    created_at: '2026-08-27T05:18:48Z',
  },
  {
    id: 'em-007',
    message_id: 'msg-007-housing',
    thread_id: 'thread-ops-7',
    sender: 'admin@college-housing.org',
    subject: 'Room Inspection Notice - Block B',
    body: 'Notice to all residents of Block B: Annual room inspections and fire safety checks will occur today between 10:00 AM and 2:00 PM. Please ensure clear pathways to windows and balconies.',
    category: 'Operations',
    ai_priority: 'MEDIUM',
    final_priority: 'HIGH',
    action_required: true,
    action: 'Ensure room cleanliness and pathway access before 10 AM',
    deadline: '2026-08-27',
    summary: 'Block B room inspection scheduled for today between 10 AM and 2 PM.',
    confidence: 0.92,
    days_remaining: 0,
    deadline_status: 'TODAY',
    should_alert: false,
    validation_status: 'VALID',
    received_at: '2026-08-27T09:45:30Z',
    created_at: '2026-08-27T09:45:33Z',
  },
  {
    id: 'em-003',
    message_id: 'msg-003-aws',
    thread_id: 'thread-fin-3',
    sender: 'billing@aws-billing-notify.com',
    subject: 'Invoice #INV-2026-8941 for Cloud Services Due',
    body: 'Greetings, Your monthly cloud infrastructure invoice of $1,420.50 has been generated. The scheduled payment will be processed on September 02, 2026.',
    category: 'Finance',
    ai_priority: 'MEDIUM',
    final_priority: 'MEDIUM',
    action_required: true,
    action: 'Review invoice charges and ensure corporate credit card balance',
    deadline: '2026-09-02',
    summary: 'Monthly cloud infrastructure invoice of $1,420.50 due on September 02, 2026.',
    confidence: 0.94,
    days_remaining: 6,
    deadline_status: 'THIS WEEK',
    should_alert: false,
    validation_status: 'VALID',
    received_at: '2026-08-26T06:30:22Z',
    created_at: '2026-08-26T06:30:25Z',
  },
  {
    id: 'em-005',
    message_id: 'msg-005-lib',
    thread_id: 'thread-edu-5',
    sender: 'library@university.ac.in',
    subject: 'Book Due Reminder: Distributed Systems Principles',
    body: 'The book "Distributed Systems: Principles and Paradigms (3rd Edition)" checked out on August 6 is due for return on September 01. You may renew online if no holds exist.',
    category: 'Education',
    ai_priority: 'LOW',
    final_priority: 'LOW',
    action_required: true,
    action: 'Renew book online or return to university library desk',
    deadline: '2026-09-01',
    summary: 'Library book return/renewal reminder due on September 01.',
    confidence: 0.91,
    days_remaining: 5,
    deadline_status: 'THIS WEEK',
    should_alert: false,
    validation_status: 'VALID',
    received_at: '2026-08-26T16:05:12Z',
    created_at: '2026-08-26T16:05:14Z',
  },
  {
    id: 'em-009',
    message_id: 'msg-009-hr',
    thread_id: 'thread-hr-9',
    sender: 'hr-compliance@portal.corp',
    subject: 'Action Required: Submit Annual Workplace Ethics Sign-off',
    body: 'All team members must complete and electronically sign the 2026 Workplace Ethics & Conduct acknowledgment module before September 10.',
    category: 'Compliance',
    ai_priority: 'MEDIUM',
    final_priority: 'MEDIUM',
    action_required: true,
    action: 'Complete ethics course module and sign digital form',
    deadline: '2026-09-10',
    summary: 'Mandatory workplace ethics training module sign-off due by September 10, 2026.',
    confidence: 0.95,
    days_remaining: 14,
    deadline_status: 'LATER',
    should_alert: false,
    validation_status: 'VALID',
    received_at: '2026-08-25T10:00:15Z',
    created_at: '2026-08-25T10:00:18Z',
  },
  {
    id: 'em-006',
    message_id: 'msg-006-hn',
    thread_id: 'thread-news-6',
    sender: 'newsletter@hackernews-digest.xyz',
    subject: 'HackerNews Weekly Tech Radar #342',
    body: 'Top stories this week: Open-source local LLM inference optimizations, WebAssembly SQLite benchmarks, and modern micro-frontend architectures.',
    category: 'Newsletter',
    ai_priority: 'LOW',
    final_priority: 'LOW',
    action_required: false,
    action: null,
    deadline: null,
    summary: 'Weekly tech news digest covering LLMs, WASM, and web architectures.',
    confidence: 0.88,
    days_remaining: null,
    deadline_status: null,
    should_alert: false,
    validation_status: 'VALID',
    received_at: '2026-08-25T11:20:00Z',
    created_at: '2026-08-25T11:20:02Z',
  },
  {
    id: 'em-008',
    message_id: 'msg-008-rg',
    thread_id: 'thread-res-8',
    sender: 'noreply@researchgate-updates.net',
    subject: 'New citation for your paper on Neural Graph Transformers',
    body: 'Your paper has been cited in "A Survey on Scalable Graph Learning Algorithms". Check the citation graph and metrics.',
    category: 'Research',
    ai_priority: 'LOW',
    final_priority: 'LOW',
    action_required: false,
    action: null,
    deadline: null,
    summary: 'Paper citation notification from ResearchGate.',
    confidence: 0.85,
    days_remaining: null,
    deadline_status: null,
    should_alert: false,
    validation_status: 'VALID',
    received_at: '2026-08-24T14:10:00Z',
    created_at: '2026-08-24T14:10:03Z',
  },
  {
    id: 'em-010',
    message_id: 'msg-010-amazon',
    thread_id: 'thread-ship-10',
    sender: 'shipment-tracking@amazon.com',
    subject: 'Your order #408-98213 has shipped',
    body: 'Your order containing "Wireless Mechanical Keyboard" has shipped via Expedited Delivery. Expected arrival date is August 29.',
    category: 'Orders',
    ai_priority: 'LOW',
    final_priority: 'LOW',
    action_required: false,
    action: 'Track package arrival on Amazon dashboard',
    deadline: '2026-08-29',
    summary: 'Amazon order shipment notification. Expected delivery on August 29.',
    confidence: 0.97,
    days_remaining: 2,
    deadline_status: '2 DAYS LEFT',
    should_alert: false,
    validation_status: 'VALID',
    received_at: '2026-08-27T11:05:00Z',
    created_at: '2026-08-27T11:05:02Z',
  }
];

